apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-develop
  namespace: develop
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: glaucioww@gmail.com
    privateKeySecretRef:
      name: letsencrypt-develop
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik