apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-shop-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owasp-shop
  template:
    metadata:
      labels:
        app: owasp-shop
    spec:
      containers:
        - name: owasp-shop
          image: bkimminich/juice-shop:latest
          ports:
            - containerPort: 3000