apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
            - hostPort: 8080