apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yml
  - namespace.yml
  - certificate.yml
  - cluster-issuer.yml
  - deployment.yml
  - ingress.yml
  - service.yml